### ISSUE TITLE
Update code of conduct link

### ISSUE THREAD

**Issue by wimo7083** [OperationCode/operationcode_pyback#55]
old: https://github.com/OperationCode/community/blob/master/code_of_conduct.md
new: https://github.com/OperationCode/operationcode_docs/blob/master/community/code_of_conduct.md

Current link is to an old version. New one in progress. Need to update this.

**Comment by kryptc** [comment]
Hi, if the new version is complete, can I work on this issue?

**Comment by wimo7083** [comment]
Yeah, you can work on this. Let me know if you run into any issues.

**Comment by wimo7083** [comment]
The incorrect file is found here:

https://github.com/OperationCode/operationcode_pyback/blob/7b8c5ab7f99c7b010271eba997299c049750e16a/ocbot/pipeline/handlers/newmember.py

this link: https://op.co.de/code-of-conduct|Code of Conduct
will resolve to the correct value.
